<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Firebase.Authentication" Version="2.0.1" />
    <PackageReference Include="Aspose.PDF" Version="25.4.0" />
    <PackageReference Include="Firebase.Database" Version="1.0.0" />
    <PackageReference Include="FirebaseAdmin" Version="2.2.0" />
    <PackageReference Include="FirebaseAdminAuthentication.DependencyInjection" Version="1.1.0" />
    <PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.68.0.3624" />
    <PackageReference Include="Google.Cloud.AIPlatform.V1" Version="3.27.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.9.0" />
    <PackageReference Include="Google.Cloud.Language.V1" Version="3.7.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.0.0" />
    <PackageReference Include="itext7" Version="9.0.0" />
    <PackageReference Include="JWT" Version="10.1.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.3" />
    <PackageReference Include="NewsAPI" Version="0.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ScottPlot" Version="4.1.44" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

</Project>
